parameters:
    jb_fileuploader.validator_chain.class: Jb\Bundle\FileUploaderBundle\Service\ValidatorChain
    jb_fileupload.image.validator.class: Jb\Bundle\FileUploaderBundle\Service\Validator\ImageValidator
    jb_fileupload.image.crop.class: Jb\Bundle\FileUploaderBundle\Service\Validator\CropValidator
    jb_fileuploader.validator.manager.class: Jb\Bundle\FileUploaderBundle\Service\ValidatorManager
    jb_fileupload.file_owner.validator.class: Jb\Bundle\FileUploaderBundle\Service\Validator\Constraints\FileOwnerValidator

services:
    jb_fileuploader.validator.manager:
        class: "%jb_fileuploader.validator.manager.class%"
        arguments:
            - @jb_fileuploader.validator_chain
            - @jb_fileuploader.endpoint_configuration

    jb_fileuploader.validator_chain:
        class: "%jb_fileuploader.validator_chain.class%"

    jb_fileupload.image.validator:
        class: "%jb_fileupload.image.validator.class%"
        tags:
            - { name: jb_fileuploader.validator, alias: Image }

    jb_fileupload.crop.validator:
        class: "%jb_fileupload.image.crop.class%"
        tags:
            - { name: jb_fileuploader.validator, alias: Crop }

    jb_fileupload.file_owner.validator:
        class: %jb_fileupload.file_owner.validator.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
        tags:
            - { name: validator.constraint_validator, alias: jb_file_owner }